### PR TITLE
Hot start cv

### PR DESCRIPTION
**Pull request by lbybee**
This branch isn't ready to merge but I want to go ahead and create a PR to keep things organized.

An issue I'm running into with real-world regularized estimation problems is that when doing CV the grid search sometimes tries a regularizing constant which leads to singularity issues with the `Gamma` estimates.  To get around this, I'm updating the CV algorithm to stop when the regularizer tries to zero out too many coefficients.

This does change things such that the parallelization now happens over the training/test samples and each alpha is tested sequentially.  One nice side effect of this is that we can use a "hot-start" approach, which feeds the estimated `Gamma`, `Factor` values from the previous step into future cross-validation steps (speeds up the convergence some).  

Will say more on this once things are finalized.

### CODE REVIEW

**Comment by matbuechner** [comment]
This sounds like a great feature to add. What exactly do you mean by "zero out too many coefficients", i.e. how is too many defined?

**Comment by lbybee** [comment]
If you choose a large enough regularizing constant (`alpha` in our case) then you can end up with linearly dependent columns in `Gamma` (too many elements have been zeroed out).  In terms of the implementation, I'm catching the LinAlgError which is thrown by our attempted Cholesky decomposition when this happens.

Since each training/test partition is fit separately (this is where the parallelization can happen), when this LinAlgError is caught we stop attempting larger `alpha` values and return the MSE path up to that point.

Currently, `fit_cv` (which essentially replaces the earlier `fit_path` method) returns a matrix of MSEs where columns correspond to training/test partitions and rows correspond to `alpha` values.  Since the `alpha` path for each training/test partition may stop at different points, rows after a given training/test partition stopped contain NaNs.

It might make sense to do some more handling of this matrix internally (e.g. instead of returning the entire matrix, drop rows which contain a certain number of NaNs and then calculate the mean for each `alpha`).  I'm still thinking about this (open to input) but figure it makes sense to return too much instead of too little to start.

Let me know if any of that isn't clear.

**Comment by lbybee** [comment]
While I'm discussing this, here is something of a roadmap for what I'd like to have together before I'm really happy with the cross-validation approach:

1. We should provide some mechanism to properly scale the possible `alpha` path based on the data.
2. Instead of returning the MSE matrix we should provide some aggregates as well as something like a path of full data fits.

For a lot of these, I'm digging into how glmnet handles their cross-validation because I think we can follow that approach closely.

**Comment by lbybee** [comment]
Closing this for now as this approach isn't currently active.

**Pull request closed without merging**
